#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-hypothesis
Version  : 4.14.2
Release  : 274
URL      : https://files.pythonhosted.org/packages/82/5b/f46e7251a2077ef9a3d079a19997effcbd02b62424561b17ceead3400d3e/hypothesis-4.14.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/82/5b/f46e7251a2077ef9a3d079a19997effcbd02b62424561b17ceead3400d3e/hypothesis-4.14.2.tar.gz
Summary  : A library for property based testing
Group    : Development/Tools
License  : MPL-2.0
Requires: deprecated-hypothesis-python = %{version}-%{release}
Requires: attrs
Requires: dpcontracts
Requires: enum34
Requires: lark-parser
Requires: numpy
Requires: pandas
Requires: python-dateutil
Requires: pytz
BuildRequires : attrs
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython
BuildRequires : setuptools-python

%description
==========
Hypothesis
==========
Hypothesis is an advanced testing library for Python. It lets you write tests which
are parametrized by a source of examples, and then generates simple and comprehensible
examples that make your tests fail. This lets you find more bugs in your code with less
work.

%package legacypython
Summary: legacypython components for the deprecated-hypothesis package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-hypothesis package.


%package python
Summary: python components for the deprecated-hypothesis package.
Group: Default

%description python
python components for the deprecated-hypothesis package.


%prep
%setup -q -n hypothesis-4.14.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554320738
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
